theme: minima
title: JURIX 2023
description: 36th International Conference on Legal Knowledge and Information Systems

header_pages:
  - index.md
  - calls.md
  - committees.md
  - speakers.md
  - program.md
  - workshops.md
  - demo.md
  - proceedings.md
  - practicalities.md
  - contact.md
